[package]
name = "btstats"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.48", features = ["derive"] }

[build-dependencies]
bindgen = "0.69.4"

[dev-dependencies]
tempfile = "3"
insta = "1.39.0"
